### ISSUE TITLE
Fix hiding of dependent fields

### ISSUE THREAD

**Issue by joergmoldenhauer** [ContaoBayern/contao-member-contact-settings#23]
Dependent fields are not hidden, when the parent field is unchecked.

**Comment by joergmoldenhauer** [comment]
This is not really a JavaScript bug. The problem is in the "initializeDependencies" method of the "FieldDependencyManager" class. In this method we take all fields defined in the DCAs "dependents" array regardless if they are actually used by the frontend module.

For example if the registration module does not use the field "country" it is still in our dependents. This causes a JavaScript error as the script is trying to modify a field which does not exist.

So we simply need to remove all fields from our depents which are not used by the frontend module. I already prepared a commit.

**Comment by fiedsch** [comment]
Sounds good and seems to work.

Note to self: I changed the version constraint in the `composer.json` file to read

```
"contaobayern/contao-member-contact-settings": "dev-master#77cfcd5c4e3839b7b0f0fa4f66b13f5508ba90e1",
```

in order to install this version with the contao manager
