### ISSUE TITLE
Ignore fields which are mandatory by default

### ISSUE THREAD

**Issue by joergmoldenhauer** [ContaoBayern/contao-member-contact-settings#28]
A principle of our extension is not to alter fields which are mandatory by default. They shall keep their mandatory status wether the "parent" field is checked or unchecked.

At the end of our README we made a comment that a user should not set a field which is mandatory by default to be dependent of another field.

I think there is an easy way to prevent the user from causing an unwanted effect. In our "FieldDependencyManager" class we could simply ignore fields which are mandatory by default.

**Comment by joergmoldenhauer** [comment]
@fiedsch What's your opinion about this?

**Comment by fiedsch** [comment]
This Sounds reasonable. Do we easily „know“ which fields this would be?

**Comment by joergmoldenhauer** [comment]
That's very easy. They have `mandatory => true` in DCA configuration.

**Comment by fiedsch** [comment]
First thought: we have to take care of that in our `FieldDependencyManager`. 

Reading the code makes me think that we don't have to do anything as the only action there is: "set a field with original `mandatory` status is `false` to `true` if the corresponding (parent) checkbox is checked". In other words: if the (parent) checkbox is not checked, we do not change anything.

The only problem I see: do not hide a field that is mandatory by default if the parent checkbox is unchecked. This is probably what we meant---but did not correctly say---in the README. 

Addition: the fields controlled by JS are initialized like so: 
```php
# ModulePersonalData.php and ModuleRegistration.php
$objTemplateJquery->dependencies = $fieldDependencyManager->getDependenciesJson();
```
We might want to change `FieldDependencyManager::initializeDependencies()` to not include fields with original `mandatory == true` status.

Example: `phone` would always be mandatory. Then the JS code should read like this (with  `phone` not in the `mandatory` and `visibility` array
```js
 dependencies: {
   "contactLetter": {
     "mandatory":["street","postal","city"],
     "visibility":["street","postal","city"]
   },
  "contactPhone":{
     "mandatory":[],
     "visibility":[]
  },
  "contactFax":{
     "mandatory":["fax"],
     "visibility":["fax"]
  }
}

**Comment by joergmoldenhauer** [comment]
You are right. Skipping mandatory fields in `intializeDependencies()` is exactly what I had in mind when I opened this issue.

As a consequence we do not need to track the original mandatory status for our reset anymore (it will always be `false`). We just need to keep a list of names of fields we change to be mandatory and remove the mandatory status in our reset. So `$originalFieldValues` will be replaced by `$changedFields` (or some name like that).

Maybe we can also find a way not to include fields which have an empty list of dependencies (like `contactPhone` in your example).

**Comment by joergmoldenhauer** [comment]
I implemented this in branch "feature-ignore-fields".

@fiedsch Can you check it please?

**Comment by fiedsch** [comment]
Installed `dev-master#ba55dbf` in my local Contao Installation. Works as expected 🎉
