### ISSUE TITLE
Add JavaScript validation

### ISSUE THREAD

**Issue by joergmoldenhauer** [ContaoBayern/contao-member-contact-settings#4]
To enhance the user experience our frontend forms (registration and data editing) should be validated in JavaScript first before we send them.

**Comment by joergmoldenhauer** [comment]
don't forget to remove the `novalidate` attribute from the template

**Comment by joergmoldenhauer** [comment]
@fiedsch I will implement this at this weekend in case we don't get any negative feedback from the version 0.1.0 testers.

**Comment by fiedsch** [comment]
@joergmoldenhauer I will push my current work tonight, so you can build on that

**Comment by fiedsch** [comment]
see assets/fielddependencies.js -- hope this is helpful.

**Comment by joergmoldenhauer** [comment]
@fiedsch Thanks for your current work. I will build upon it. I will also create a branch "0.2.0" so we can push all our work on version 0.2.0 there and merge it into master when we are finished.

**Comment by joergmoldenhauer** [comment]
@fiedsch I transformed your code into a generic jQuery plugin which takes the dependencies as JSON data. I added this JavaScript to the registration module. It has to be tested a little more. Also it would be nice to add an error message which tells the user why a dependent field is required (that's because he checked the corresponding checkbox). If the script is finished it can be added to the personal data module. I will continue this work next weekend.

Don't be surprised, I removed the email dependency as it is no real dependency. E-Mail is always mandatory. By removing this dependency we do not need to create a special implementation for email in JavaScript.

**Comment by joergmoldenhauer** [comment]
I just saw that there are a few more classes and spans added in Contao when a field is mandatory. Also there is no space before the `*`. I will look into these deails next weekend, too.

**Comment by joergmoldenhauer** [comment]
Note: for now only tableless form layout is supported.

**Comment by fiedsch** [comment]
Two comments: 

1. in `hideDependentFields` the property `required` is set to `false` by `$(this).prop('required', false);`. We assume that this was the original setting which we changed to `true` in `showDependentFields()`.
But: it might have been `true ` (i.e. `required`) in the beginning (see for example the `email` field. This might be the same for oteh fields if the user changes Contao's original DCA. 

2. in addition to making the dependent fields mandatory we currently also hide and show them. Is this the required behaviour? I think it would be sufficient to only change the mandatory setting. Example: a user might want to enter his postal details (`street`, `postal` and `city`) without  also allowing `contactLetter`.

**Comment by joergmoldenhauer** [comment]
1. That's because we hide and show the fields, too. A hidden field must not be mandatory. In fact I think we have two kinds of dependencies which should be treated seperately: displaying a field and setting it to mandatory. So I think just setting the `dependents` in the DCA is not enough. We need to have two arrays. One to specify the fields which shall be shown/hidden according to the checkbox value and one for the fields that shall be set to mandatory according to the checkbox value. Then a field could be shown/hidden without the need that has to be mandatory to be shown. As for the email: I removed this dependency completly, as it is no real dependency. You always need an email address for registration. That's the same for all fields which are mandatory in the beginning. If a field is mandatory by itself, it should not be dependent from one of the checkboxes and should never be hidden.

2. It is the desired behaviour according to the request for this extension. The dependent fields shall only appear when the corresponding checkbox is checked. Perhaps we could make it more flexible by using the two dependencies described in 1. Then a user could change the behaviour in his dcaconfig. In the future we could also implement setting this in the module configuration.

**Comment by fiedsch** [comment]
> That's because we hide and show the fields, too. A hidden field must not be mandatory. 

Or you put it the other way round: A mandatory field must not be hidden ;-)

To me, restoring the original setting still makes sense. And for being consistent I would work on all fields specified in the DCA regardless of some external logic like "email is always mandatory". We simply restore mandatory to mandatory which causes nearly no cost, but has the benefit that the code (the logic) is easier to understand.

In addition: how do we know that "email is always mandatory"? The way we have it now is like a hard coded value, which is always bad.

I completely agree with your "We need to have two arrays" because making fileds mandarory and showing/hiding them are two seperate tasks. They might correlate but they are not thee necessarily same.

**Comment by joergmoldenhauer** [comment]
You are right. So we will use two arrays and reset the "mandatory" state to it's original setting.

**Comment by joergmoldenhauer** [comment]
Here is some other thing, we shall not forget: If the user checks a checkbox and fills out the dependent fields, there is a chance, he might change his mind and uncheck the checkbox again. Then the data from the dependent fields should not be send.

**Comment by fiedsch** [comment]
This is exactly what I had in mind in my "Two comments:" comment.

I see it that way: in this situation the user's answer is: "do not contact me via letter, but this is my postal address".

It feels like the is no use case for that, but you never know ;-)

If we do not want to submit the fields (but keep the values as the user might change his mind again) adding a disabled attribute might help, because disabled fields are never submited (IIRC). But only when also hiding the fields, because otehwise the user will not understand what is happening.

**Comment by joergmoldenhauer** [comment]
Setting a field to be disabled when it is hidden is a good idea.

**Comment by joergmoldenhauer** [comment]
In the last commit I implemented separation of mandatory status and visibility.

In JavaScript we now only control fields which are not mandatory by default. Fields which are already mandatory shall not be influenced by our JavaScript (they always have to be mandatory and visible).

I think there needs to be some testing and refactoring. Also the missing stuff which Contao adds to a required field has to be considered in our JavaScript, too.
