### ISSUE TITLE
Make field dependencies editable

### ISSUE THREAD

**Issue by joergmoldenhauer** [ContaoBayern/contao-member-contact-settings#5]
It would be nice if the field dependencies, which are hard coded right now, can be set in Contao backend.

**Comment by fiedsch** [comment]
As a first step I would make it configurable via DCA only. This way, users of this extension could change the settings by writing their own DCA settings (e.g. in `dcaconfig.php`).

If they wanted new fields they would have to do that anyway!

**Comment by fiedsch** [comment]
Implemented what I had in mind. @joergmoldenhauer could you please have a look?

**Comment by joergmoldenhauer** [comment]
Ah, I see. That's a very good idea.
