### ISSUE TITLE
Rename "contactPost" DCA field

### ISSUE THREAD

**Issue by joergmoldenhauer** [ContaoBayern/contao-member-contact-settings#9]
The DCA field "contactPost" should be renamed because it is not proper english. We should rename while we still have time (meaning before we release a stable production version people actually use).

@fiedsch what do you think is a proper name? My suggestions are "contactPostal" or "contactRegularMail".

**Comment by fiedsch** [comment]
I would use contactPostal, but the I found that Contao calls the areaCode (Postleitzahl) postal in `tl_member`. I'm fear that this is confusing, so I would opt for `contactLetter`.

**Comment by joergmoldenhauer** [comment]
Ok, we will use "contactLetter". Please do not close the issue yet, it has to be implemented first. I removed the discussion label.

**Comment by fiedsch** [comment]
I already did that ;-)

**Comment by joergmoldenhauer** [comment]
I missed the commit, sorry.
